### ISSUE TITLE
npm run down fails

### ISSUE THREAD

**Issue by C24IO** [aws-samples/aws-sagemaker-build#16]
chzar:~/efs/C/John/aws-sagemaker-build (master) $ npm run down

> sagebuild@2.0.0 down /home/ec2-user/efs/C/John/aws-sagemaker-build
> node ./sagebuild/bin/delete.js

SageBuild-test-1
Waiting on stack:SageBuild-test-1
✖ SageBuild-test-1:Stack with id SageBuild-test-1 does not exist
(node:9505) UnhandledPromiseRejectionWarning: ValidationError: Stack with id SageBuild-test-1 does not exist
    at Request.extractError (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/efs/C/John/aws-sagemaker-build/node_modules/aws-sdk/lib/request.js:38:9)
(node:9505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JohnCalhoun** [comment]
This is fixed in latest version

**Comment by sstoeckel** [comment]
When does this later version be released? I still got this issue.
