### ISSUE TITLE
Unable to find config directory

### ISSUE THREAD

**Issue by jpbarto** [aws-samples/aws-sagemaker-build#18]
When running `npm run up` the following results:

```bash
> sagebuild@3.0.0 up /home/ubuntu/environment/aws-sagemaker-build
> make && ./bin/upload.sh && ./templates/main/bin/launch.js

mkdir -p build; mkdir -p build/lambda; mkdir -p build/templates
for l in templates/activo templates/main; do    \
        make -C $l;                     \
done;
make[1]: Entering directory '/home/ubuntu/environment/aws-sagemaker-build/templates/activo'
./bin/check.js 
module.js:550
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/environment/aws-sagemaker-build/templates/activo/bin/aws.js:2:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Makefile:3: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/ubuntu/environment/aws-sagemaker-build/templates/activo'
make[1]: Entering directory '/home/ubuntu/environment/aws-sagemaker-build/templates/main'
rm build/notebooks.zip ; cd SageMakerNotebook/notebooks && zip -r ../../../../build/notebooks.zip .
rm: cannot remove 'build/notebooks.zip': No such file or directory
updating: mxnet/ (stored 0%)
updating: mxnet/input.html (deflated 65%)
updating: mxnet/mxnet_mnist.ipynb (deflated 67%)
updating: mxnet/mnist.py (deflated 61%)
updating: amazon/ (stored 0%)
updating: amazon/linear_learner_mnist.ipynb (deflated 67%)
updating: tensorflow/ (stored 0%)
updating: tensorflow/utils.py (deflated 59%)
updating: tensorflow/setup.sh (deflated 61%)
updating: tensorflow/mnist.py (deflated 66%)
updating: tensorflow/daemon.json (deflated 42%)
updating: tensorflow/tensorflow_distributed_mnist.ipynb (deflated 69%)
updating: HyperParameterOptimization/ (stored 0%)
updating: HyperParameterOptimization/hpo_mxnet_mnist.ipynb (deflated 67%)
updating: HyperParameterOptimization/input.html (deflated 65%)
updating: HyperParameterOptimization/mnist.py (deflated 62%)
./bin/check.js 
module.js:550
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/environment/aws-sagemaker-build/templates/main/bin/aws.js:2:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Makefile:3: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/ubuntu/environment/aws-sagemaker-build/templates/main'
Makefile:21: recipe for target 'templates' failed
make: *** [templates] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sagebuild@3.0.0 up: `make && ./bin/upload.sh && ./templates/main/bin/launch.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the sagebuild@3.0.0 up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-06-17T13_49_20_803Z-debug.log```

**Comment by JohnCalhoun** [comment]
looking into this now
